// Generated by Opus 4.6 on 3/30/26
// Prompt:  I want you to this inventory system I have in unity. I want to have a hotbar that grows dynamically with the number of items the player has in their inventory.
// Ie if the player has no items there is no hotbar, if the player has one item type there is a single box in the hotbar with that items icon, etc

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class HotbarController : MonoBehaviour
{
    public InventoryManager inventoryManager;
    public GameObject hotbarSlotPrefab;
    public Transform hotbarParent;
    public GameObject hotbarRoot;

    private int selectedIndex = 0;
    private int lastItemHash = -1;

    void Update()
    {
        // Detect inventory changes by checking a simple fingerprint
        int currentHash = ComputeInventoryHash();
        if (currentHash != lastItemHash)
        {
            lastItemHash = currentHash;
            RefreshHotbar();
        }

        if (hotbarParent.childCount == 0) return;

        // Scroll wheel selection
        float scroll = Input.GetAxis("Mouse ScrollWheel");
        if (scroll > 0f)
        {
            selectedIndex--;
            if (selectedIndex < 0) selectedIndex = hotbarParent.childCount - 1;
            UpdateSelection();
        }
        else if (scroll < 0f)
        {
            selectedIndex++;
            if (selectedIndex >= hotbarParent.childCount) selectedIndex = 0;
            UpdateSelection();
        }

        // Number keys 1-9
        for (int i = 0; i < 9 && i < hotbarParent.childCount; i++)
        {
            if (Input.GetKeyDown(KeyCode.Alpha1 + i))
            {
                selectedIndex = i;
                UpdateSelection();
            }
        }
    }

    private int ComputeInventoryHash()
    {
        List<ItemData> items = inventoryManager.items;
        int hash = items.Count;
        for (int i = 0; i < items.Count; i++)
        {
            hash = hash * 31 + items[i].quantity;
            hash = hash * 31 + (items[i].itemName != null ? items[i].itemName.GetHashCode() : 0);
        }
        return hash;
    }

    private void RefreshHotbar()
    {
        foreach (Transform child in hotbarParent)
        {
            Destroy(child.gameObject);
        }

        List<ItemData> items = inventoryManager.items;
        hotbarRoot.SetActive(items.Count > 0);
        if (items.Count == 0) return;

        for (int i = 0; i < items.Count; i++)
        {
            GameObject slot = Instantiate(hotbarSlotPrefab, hotbarParent);
            slot.GetComponent<HotbarSlot>().Setup(items[i]);
        }

        selectedIndex = Mathf.Clamp(selectedIndex, 0, items.Count - 1);
        UpdateSelection();
    }

    private void UpdateSelection()
    {
        for (int i = 0; i < hotbarParent.childCount; i++)
        {
            hotbarParent.GetChild(i).GetComponent<HotbarSlot>().SetSelected(i == selectedIndex);
        }
    }

    public ItemData GetSelectedItem()
    {
        if (hotbarParent.childCount == 0) return null;
        return hotbarParent.GetChild(selectedIndex).GetComponent<HotbarSlot>().GetItem();
    }
}