// Generated by Opus 4.6 on 3/30/26
// Prompt:  I want you to this inventory system I have in unity. I want to have a hotbar that grows dynamically with the number of items the player has in their inventory.
// Ie if the player has no items there is no hotbar, if the player has one item type there is a single box in the hotbar with that items icon, etc

using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class HotbarSlot : MonoBehaviour
{
    public Image iconImage;
    public TextMeshProUGUI quantityText;
    public GameObject selectionHighlight;

    private ItemData itemData;

    public void Setup(ItemData data)
    {
        itemData = data;
        iconImage.sprite = data.icon;
        quantityText.text = data.quantity > 1 ? data.quantity.ToString() : "";
    }

    public void SetSelected(bool selected)
    {
        selectionHighlight.SetActive(selected);
    }

    public ItemData GetItem()
    {
        return itemData;
    }
}