// Generated by Gemini 3 Fast on 3/2/26
//Prompt: I am working with unity. I want to create an inventory.
//There will be a hard coded set of items in the inventory.
//For each item, it will have a name, a description, and a quantity.
//For the UI, I want a scrollable set of blocks. Each block will correspond to one item type.
//Players will see an icon, the item name, the description, and have the option to use the item. 
//The game should pause when the inventory is opened and resume when it restarts.

// Prompt 2 (3/3/26): Update all the scripts to incorperate stacking.

using System.Collections.Generic;
using UnityEngine;

public class InventoryManager : MonoBehaviour
{
    public List<ItemData> items = new List<ItemData>();
    public GameObject itemSlotPrefab;
    public Transform contentParent;
    public GameObject inventoryUI;

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.I))
        {
            ToggleInventory();
        }
    }

    public void AddItem(ItemData newData)
    {
        // Check if we already have this item in our list
        ItemData existingItem = items.Find(i => i.itemName == newData.itemName);

        if (existingItem != null)
        {
            existingItem.quantity += newData.quantity;
        }
        else
        {
            // Add a copy so we don't edit the actual file in the Assets folder
            ItemData clone = newData.GetCopy();
            items.Add(clone);
        }

        if (inventoryUI.activeSelf) RefreshUI();
    }

    public void RefreshUI()
    {
        // Clear old UI slots
        foreach (Transform child in contentParent)
        {
            Destroy(child.gameObject);
        }

        // Create new UI slots for current items
        foreach (ItemData item in items)
        {
            GameObject slot = Instantiate(itemSlotPrefab, contentParent);
            slot.GetComponent<ItemSlot>().Setup(item, this);
        }
    }

    public void ToggleInventory()
    {
        bool isActive = !inventoryUI.activeSelf;
        inventoryUI.SetActive(isActive);

        if (isActive) RefreshUI();

        Time.timeScale = isActive ? 0f : 1f;
    }
}