// Generated by Gemini 3 Fast on 3/2/26
//Prompt: I am working with unity. I want to create an inventory.
//There will be a hard coded set of items in the inventory.
//For each item, it will have a name, a description, and a quantity.
//For the UI, I want a scrollable set of blocks. Each block will correspond to one item type.
//Players will see an icon, the item name, the description, and have the option to use the item. 
//The game should pause when the inventory is opened and resume when it restarts.

using System.Collections.Generic;
using UnityEngine;

public class InventoryManager : MonoBehaviour
{
    public List<ItemData> items; // Drag your Item assets here in the Inspector
    public GameObject itemSlotPrefab;
    public Transform contentParent;
    public GameObject inventoryUI;

    void Start()
    {
        PopulateInventory();
        inventoryUI.SetActive(false);
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.I)) // Toggle inventory
        {
            ToggleInventory();
        }
    }

    void PopulateInventory()
    {
        foreach (ItemData item in items)
        {
            GameObject slot = Instantiate(itemSlotPrefab, contentParent);
            // Assume the prefab has an 'ItemSlot' script to set the text/icons
            slot.GetComponent<ItemSlot>().Setup(item);
        }
    }

    public void ToggleInventory()
    {
        bool isActive = !inventoryUI.activeSelf;
        inventoryUI.SetActive(isActive);

        // Pause/Resume Logic
        Time.timeScale = isActive ? 0f : 1f;
    }
}