// Generated by Gemini 3 Fast on 3/2/26
//Prompt: I am working with unity. I want to create an inventory.
//There will be a hard coded set of items in the inventory.
//For each item, it will have a name, a description, and a quantity.
//For the UI, I want a scrollable set of blocks. Each block will correspond to one item type.
//Players will see an icon, the item name, the description, and have the option to use the item. 
//The game should pause when the inventory is opened and resume when it restarts.

// Prompt 2 (3/3/26): Update all the scripts to incorperate stacking.

using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class ItemSlot : MonoBehaviour
{
    public Image iconImage;
    public TextMeshProUGUI nameText;
    public TextMeshProUGUI descriptionText;
    public TextMeshProUGUI quantityText;

    private ItemData currentItem;
    private InventoryManager manager;

    public void Setup(ItemData newItem, InventoryManager m)
    {
        currentItem = newItem;
        manager = m;

        nameText.text = newItem.itemName;
        descriptionText.text = newItem.description;
        quantityText.text = "x" + newItem.quantity.ToString();
        iconImage.sprite = newItem.icon;
    }

    public void OnUseButtonClicked()
    {
        if (currentItem.quantity > 0)
        {
            currentItem.quantity--;
            Debug.Log($"Used {currentItem.itemName}. Remaining: {currentItem.quantity}");

            if (currentItem.quantity <= 0)
            {
                manager.items.Remove(currentItem);
            }

            manager.RefreshUI(); // Update the labels and list
        }
    }
}