// Generated by Gemini 3 Fast on 3/2/26
//Prompt 1: I am working with unity. I want to create an inventory.
//There will be a hard coded set of items in the inventory.
//For each item, it will have a name, a description, and a quantity.
//For the UI, I want a scrollable set of blocks. Each block will correspond to one item type.
//Players will see an icon, the item name, the description, and have the option to use the item. 
//The game should pause when the inventory is opened and resume when it restarts.

// Prompt 2 (3/3/26): Update all the scripts to incorperate stacking.

using UnityEngine;

[CreateAssetMenu(fileName = "New Item", menuName = "Inventory/Item")]
public class ItemData : ScriptableObject
{
    public string itemName;
    public Sprite icon;
    [TextArea] public string description;
    public int quantity = 1;

    // We use a clone of the data so we don't permanently change the Project Asset
    public ItemData GetCopy()
    {
        return Instantiate(this);
    }
}