// Generated by Gemini 3 Fast on 3/3/26
//Prompt: What if these items need to exist in the world. Should they instead be game objects?

using UnityEngine;

public class WorldItem : MonoBehaviour
{
    public ItemData itemData;
    public float pickupRange = 3.0f; // The max distance for pickup

    private void OnMouseDown()
    {
        // 1. Find the player object
        GameObject player = GameObject.FindWithTag("Player");

        if (player != null)
        {
            // 2. Calculate distance
            float distance = Vector3.Distance(transform.position, player.transform.position);

            // 3. Only proceed if close enough
            if (distance <= pickupRange)
            {
                InventoryManager inventory = FindFirstObjectByType<InventoryManager>();

                if (inventory != null)
                {
                    inventory.AddItem(itemData);
                    Destroy(gameObject);
                }
            }
            else
            {
                Debug.Log("Item is too far away!");
            }
        }
        else
        {
            Debug.LogWarning("No GameObject with the tag 'Player' found in the scene!");
        }
    }
}