// Generated by Gemini 3 Fast on 3/3/26
//Prompt: What if these items need to exist in the world. Should they instead be game objects?
//Prompt (3/6/26): Can you have it so that you don't need to see the item, you just need to be within a certain range?
using UnityEngine;

public class WorldItem : MonoBehaviour
{
    public ItemData itemData;

    public void PickUp()
    {
        InventoryManager inventory = FindFirstObjectByType<InventoryManager>();

        if (inventory != null)
        {
            inventory.AddItem(itemData);
            Destroy(gameObject);
        }
    }
}