using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(CharacterController))]
public class PlayerMovement : MonoBehaviour
{
    public Camera playerCamera;
    public float walkSpeed = 6f;
    public float runSpeed = 12f;
    public float jumpPower = 7f;
    public float gravity = 10f;
    public float lookSpeed = 2f;
    public float lookXLimit = 45f;
    public float defaultHeight = 2f;
    public float crouchHeight = 1f;
    public float crouchSpeed = 3f;

    public float interactRange = 3f;
    public LayerMask interactLayer;

    private Vector3 moveDirection = Vector3.zero;
    private float rotationX = 0;
    private CharacterController characterController;

    private bool canMove = true;
    
    private InventoryManager inventoryManager;

    void Start()
    {
        characterController = GetComponent<CharacterController>();
        inventoryManager = FindFirstObjectByType<InventoryManager>();
        SetCursorState(true);
    }

    // void OnTriggerEnter(Collider other)
    // {
    //     Item item = other.GetComponent<Item>();
    //     if (item != null)
    //     {
    //         inventory.PickUp(item);
    //     }
    // }
    
    void Update()
    {
        if (inventoryManager != null && inventoryManager.inventoryUI != null)
        {
            bool isInventoryOpen = inventoryManager.inventoryUI.activeSelf;
            canMove = !isInventoryOpen;
            SetCursorState(canMove);
        }

        if (canMove && Input.GetKeyDown(KeyCode.E))
        {
            HandleInteraction();
        }

        Vector3 forward = transform.TransformDirection(Vector3.forward);
        Vector3 right = transform.TransformDirection(Vector3.right);

        bool isRunning = Input.GetKey(KeyCode.LeftShift);
        float curSpeedX = canMove ? (isRunning ? runSpeed : walkSpeed) * Input.GetAxis("Vertical") : 0;
        float curSpeedY = canMove ? (isRunning ? runSpeed : walkSpeed) * Input.GetAxis("Horizontal") : 0;
        float movementDirectionY = moveDirection.y;
        moveDirection = (forward * curSpeedX) + (right * curSpeedY);

        if (Input.GetButton("Jump") && canMove && characterController.isGrounded)
        {
            moveDirection.y = jumpPower;
        }
        else
        {
            moveDirection.y = movementDirectionY;
        }

        if (!characterController.isGrounded)
        {
            moveDirection.y -= gravity * Time.deltaTime;
        }

        if (Input.GetKey(KeyCode.R) && canMove)
        {
            characterController.height = crouchHeight;
            walkSpeed = crouchSpeed;
            runSpeed = crouchSpeed;

        }
        else
        {
            characterController.height = defaultHeight;
            walkSpeed = 6f;
            runSpeed = 12f;
        }

        characterController.Move(moveDirection * Time.deltaTime);

        if (canMove)
        {
            rotationX += -Input.GetAxis("Mouse Y") * lookSpeed;
            rotationX = Mathf.Clamp(rotationX, -lookXLimit, lookXLimit);
            playerCamera.transform.localRotation = Quaternion.Euler(rotationX, 0, 0);
            transform.rotation *= Quaternion.Euler(0, Input.GetAxis("Mouse X") * lookSpeed, 0);
        }
    }

    //Generated by Gemini 3 Fast on 3/6/26
    //Prompt: This is my player movement script. I had an old inventory system that I scrapped. How can I update it.
    void HandleInteraction()
    {
        // Find all colliders in a sphere around the player
        Collider[] closeItems = Physics.OverlapSphere(transform.position, interactRange, interactLayer);

        // DEBUG: Tells you how many things the circle found
        Debug.Log("Items found in range: " + closeItems.Length);

        float closestDistance = Mathf.Infinity;
        WorldItem closestItem = null;

        foreach (Collider col in closeItems)
        {
            WorldItem item = col.GetComponent<WorldItem>();
            if (item != null)
            {
                float dist = Vector3.Distance(transform.position, col.transform.position);
                if (dist < closestDistance)
                {
                    closestDistance = dist;
                    closestItem = item;
                }
            }
            else
            {
                // DEBUG: Tells you if it found an object but that object is missing the script
                Debug.Log("Found " + col.name + " but it has no WorldItem script!");
            }
        }

        // Pick up the single closest item found
        if (closestItem != null)
        {
            Debug.Log("Picking up: " + closestItem.itemData.itemName);
            closestItem.PickUp();
        }
    }

    void SetCursorState(bool locked)
    {
        // If movement is allowed, lock the cursor. If not (menu is open), show the cursor.
        Cursor.lockState = locked ? CursorLockMode.Locked : CursorLockMode.None;
        Cursor.visible = !locked;
    }

    // Draws the pickup radius in the Scene View for easy debugging
    private void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.yellow;
        Gizmos.DrawWireSphere(transform.position, interactRange);
    }
}