// Code generated by Gemini 3 Fast on 2/18/2026 
// Prompt: Write a Unity C# script for a 2.5D dungeon crawler enemy AI. Features: NavMesh movement with 
// Patrol, Chase, and Attack states. Include a Raycast line-of-sight check for detection. For visuals, 
// implement billboarding so the 2D sprite faces the player and switches between a 'front' and 'back' 
// sprite based on the dot product of its movement direction relative to the player.

using UnityEngine;
using UnityEngine.AI;

[RequireComponent(typeof(NavMeshAgent))]
public class DungeonEnemyAI : MonoBehaviour
{
    public enum EnemyState { Patrol, Chase, Attack }

    [Header("State Management")]
    public EnemyState currentState = EnemyState.Patrol;
    public Transform player;

    [Header("Detection Settings")]
    public float detectRange = 10f;
    public float attackRange = 2f;
    public LayerMask detectionLayers; // Set this to "Player" and "Default/Environment"

    //[Header("Patrol Settings")]
    //public Transform[] waypoints;
    //private int currentWaypointIndex = 0;

    [Header("Graphics (2.5D)")]
    public SpriteRenderer spriteRenderer;
    public Sprite frontSprite;
    public Sprite backSprite;

    private NavMeshAgent agent;

    void Start()
    {
        agent = GetComponent<NavMeshAgent>();

        // Automatically find the player if not assigned
        if (player == null)
            player = GameObject.FindGameObjectWithTag("Player").transform;
    }

    void Update()
    {
        if (player == null) return;

        float distanceToPlayer = Vector3.Distance(transform.position, player.position);
        bool canSeePlayer = HasLineOfSight(distanceToPlayer);

        // --- 1. STATE LOGIC ---
        switch (currentState)
        {
            case EnemyState.Patrol:
                HandlePatrol();
                if (canSeePlayer) currentState = EnemyState.Chase;
                break;

            case EnemyState.Chase:
                agent.SetDestination(player.position);

                if (distanceToPlayer <= attackRange)
                    currentState = EnemyState.Attack;

                // If we lose sight and get far away, go back to patrol
                if (!canSeePlayer && distanceToPlayer > detectRange)
                    currentState = EnemyState.Patrol;
                break;

            case EnemyState.Attack:
                HandleAttack();
                if (distanceToPlayer > attackRange)
                    currentState = EnemyState.Chase;
                break;
        }

        // --- 2. VISUALS (Billboarding & Sprite Swapping) ---
        UpdateVisuals();
    }

    bool HasLineOfSight(float distance)
    {
        if (distance > detectRange) return false;

        RaycastHit hit;
        Vector3 rayStart = transform.position + Vector3.up; // Eye level
        Vector3 direction = (player.position - rayStart).normalized;

        if (Physics.Raycast(rayStart, direction, out hit, detectRange, detectionLayers))
        {
            if (hit.transform.CompareTag("Player"))
            {
                return true;
            }
        }
        return false;
    }

    void HandlePatrol()
    {
        // If we don't have a destination, find a random spot nearby
        if (!agent.hasPath || agent.remainingDistance < 0.5f)
        {
            Vector3 randomDirection = Random.insideUnitSphere * 5f; // Search within 5 meters
            randomDirection += transform.position;
            NavMesh.SamplePosition(randomDirection, out NavMeshHit hit, 5f, 1);
            agent.SetDestination(hit.position);
        }
    }

    void HandleAttack()
    {
        agent.SetDestination(transform.position); // Stay put while attacking
        // Logic for dealing damage would go here
    }

    void UpdateVisuals()
    {
        // Always face the player (Billboard)
        Vector3 dirToPlayer = player.position - transform.position;
        dirToPlayer.y = 0;
        transform.rotation = Quaternion.LookRotation(-dirToPlayer);

        // Sprite Swapping based on movement direction
        if (agent.velocity.magnitude > 0.1f)
        {
            Vector3 moveDir = agent.velocity.normalized;
            Vector3 toPlayer = dirToPlayer.normalized;
            float dot = Vector3.Dot(moveDir, toPlayer);

            // If moving toward player (dot is negative), show front. 
            // If moving away (dot is positive), show back.
            spriteRenderer.sprite = (dot < 0) ? frontSprite : backSprite;
        }
    }

    // Debug tool to see the Raycast in the Scene View
    void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.yellow;
        Gizmos.DrawWireSphere(transform.position, detectRange);

        if (player != null)
        {
            Gizmos.color = Color.red;
            Gizmos.DrawLine(transform.position + Vector3.up, player.position);
        }
    }
}